<?php
/**
 * @file
 * global_taxonomy_resource_topic.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function global_taxonomy_resource_topic_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'OEMs',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => '0a850095-a7f8-4fd4-8f29-2bcedf1b3e43',
    'vocabulary_machine_name' => 'resource_topic',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Finance & Capital Markets',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => '2966a1d4-950a-417f-9622-c22d0e186616',
    'vocabulary_machine_name' => 'resource_topic',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Econonmics & Employment',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 5,
    'uuid' => '4c2cc5ac-33e3-4e2d-ba92-b88c38868e9b',
    'vocabulary_machine_name' => 'resource_topic',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Antitrust Compliance',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '50a5a6fb-59f0-42f0-88fc-eb5808c7eda0',
    'vocabulary_machine_name' => 'resource_topic',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'HR Recruiting Assistance',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 10,
    'uuid' => '5b4986f0-f52b-49a2-829a-716dddab1da8',
    'vocabulary_machine_name' => 'resource_topic',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'International Markets and Trade',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 6,
    'uuid' => '61970b92-1504-440a-827e-fbe59cd4bbdb',
    'vocabulary_machine_name' => 'resource_topic',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Operational Performance',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 9,
    'uuid' => '62aa6ddc-76e9-486a-8d60-8642afc2e25f',
    'vocabulary_machine_name' => 'resource_topic',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Business Development',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 12,
    'uuid' => '8d1bc192-0114-46de-9de6-b78b62fad36a',
    'vocabulary_machine_name' => 'resource_topic',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Emergency Response and Relief',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 13,
    'uuid' => '8d1edef1-fd0a-416e-a4ce-3343d09f7f48',
    'vocabulary_machine_name' => 'resource_topic',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Sales & Production',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => '923dc553-a51b-435d-9f6d-ee550ca27ace',
    'vocabulary_machine_name' => 'resource_topic',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Supply Chain',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => 'a3bb968d-2acf-479e-b15b-6e353d970e91',
    'vocabulary_machine_name' => 'resource_topic',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Corporate Responsibility',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 14,
    'uuid' => 'c7369a8a-be5a-4383-a55e-2a701bd49fcc',
    'vocabulary_machine_name' => 'resource_topic',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Legal',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 11,
    'uuid' => 'e2b766d8-ed0a-4067-baf0-d94b7366c32c',
    'vocabulary_machine_name' => 'resource_topic',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Public Policy',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 8,
    'uuid' => 'f63f14d7-832b-4f64-95fa-33d7a05dfef1',
    'vocabulary_machine_name' => 'resource_topic',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Energy',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 7,
    'uuid' => 'fce75ff0-af91-4303-bb55-f4862ac32ed8',
    'vocabulary_machine_name' => 'resource_topic',
    'url_alias' => array(),
  );
  return $terms;
}
