<?php
/**
 * @file
 * global_taxonomy_topics.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function global_taxonomy_topics_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Reporting',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 49,
    'uuid' => '05bc70eb-25c6-4036-82ba-a356b244def9',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Bus Safety',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 13,
    'uuid' => '062c466a-be0f-46b9-ac56-12ae944f5d05',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Tax Credit',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 23,
    'uuid' => '084dcddf-c3c3-4859-8dbf-67d3fb87eb75',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Patient Protection and Affordable Care Act',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 12,
    'uuid' => '12b9a3bf-b49f-4f70-904c-5cd2871ed3ea',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Transmission shift position sequence',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 42,
    'uuid' => '14c5fa2b-4f7a-4fd5-8dd0-3a366f2dc2f3',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Trade Enforcement Act',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 29,
    'uuid' => '29893937-1b7c-47da-8726-7aa8b1f76917',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Tax Policy',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 24,
    'uuid' => '2a9e0b4c-9a2b-40a9-bd17-ae352560855d',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Planning',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 47,
    'uuid' => '2d5a93df-688e-4a48-9656-0fdbb12efea4',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Motor Vehicle Safety Act Mandates',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 45,
    'uuid' => '2e16d974-ff95-4a12-a39a-7cfa7a5c5142',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Hydraulic and Electric Brake Systems',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 35,
    'uuid' => '404db2b4-e70d-4ab0-aabd-b67c8de62834',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Safety Inspection Program',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 17,
    'uuid' => '4219a52c-7651-4797-b57d-ce64ae8d5910',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Lamps',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 36,
    'uuid' => '4a8a8a20-634e-4bdb-92c5-352a28add501',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Conflict Minerals',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => '4f9120ba-8a2c-4800-9956-ebbaa9327de6',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Ignition Interlock Systems',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 43,
    'uuid' => '508bd7ff-2473-468f-9c74-e7c32d797282',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Small Business Credit Initiative',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 18,
    'uuid' => '6ae5c3a1-8212-4df9-918d-1914912fcc37',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Stability Control',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 50,
    'uuid' => '6c076339-08cd-4020-a3b8-2a36f2cf257e',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Rearview Mirrors',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 37,
    'uuid' => '702faefe-2427-473f-81b9-a6ef181d2128',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'AMT-Credit',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 21,
    'uuid' => '713975cd-ce9f-4e39-aa85-7976aed1c7b8',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Brake Hoses',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 33,
    'uuid' => '84db4fc8-dda4-4a8c-98d2-f66d0ecdf14f',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Policy Issues',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 52,
    'uuid' => '8a7bc034-5ed0-4b0c-8b8b-154beb84c219',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Legislative Issues',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '8f056afd-de00-453c-8ad5-82b0ed91041d',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Distracted Driving',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 14,
    'uuid' => '9843f7fa-a5f6-4e58-9b9f-151b65e1dee6',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Trade Law',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 30,
    'uuid' => '9d288c14-b311-4cb5-8e97-742e64ee5881',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Tires',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 51,
    'uuid' => 'a593ea2c-c872-4bf6-b485-ff23a3eb8a3e',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Rims',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 38,
    'uuid' => 'a77a2552-879d-4829-9951-d9a3bfba503e',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Vehicle Technology',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 26,
    'uuid' => 'a96fe421-0373-40b5-8e46-68b883a75abe',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'American Clean Energy and Security Act',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 7,
    'uuid' => 'aaba4d20-aa3f-4586-b5ca-d0656d5c4254',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Transmission Braking Effect',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 41,
    'uuid' => 'aad558ca-94d6-4432-93b5-37537207ca2a',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'AMT',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 20,
    'uuid' => 'acfed266-d8ba-42fd-a30c-4661be346934',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Health Care Reform',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 11,
    'uuid' => 'ae9f1eac-62a4-4c20-af03-7a365c7be8ac',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Srtarter Interlock',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 39,
    'uuid' => 'b03f2ef7-330d-4239-88bc-5be622759e93',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Kids & Cars Act Mandates',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 44,
    'uuid' => 'b5cc78f7-2ca3-4799-be8a-7d4e6433a37a',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Free Trade Agreements',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 27,
    'uuid' => 'b96feb11-c1e6-4677-936a-ae555b8d329f',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'FTA',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 28,
    'uuid' => 'b97bdc87-fc5d-4c49-b6c8-6dd9e6b638f0',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Programs',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 48,
    'uuid' => 'b9b38179-8cb8-4cae-b67d-2899666961f4',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Motor Vehicle Safety Act',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 15,
    'uuid' => 'ba1695d5-0ef4-4130-8ace-f88e8b07c68b',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Counterfieting',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => 'bdb964c0-9feb-49f3-9d5c-43f01a84e2ca',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Small Business Emergency Loan Relief Act',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 19,
    'uuid' => 'c2e12402-7d30-49de-9da6-6ff40fb07487',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Energy Independence and Security Act',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 9,
    'uuid' => 'c2ef76c8-b7b2-47bc-b8b0-66b7269a38a6',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Highway Bill',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 31,
    'uuid' => 'c402902a-968f-4d5d-9277-7573de464a82',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Tires',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 40,
    'uuid' => 'cb3c3700-c474-4074-b5d2-d6cc9e842ced',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Anti-idling Devices Tax Credit',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 22,
    'uuid' => 'ce7e86b9-8595-4dd5-8217-45457a261af0',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'National Safety Inspection',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 16,
    'uuid' => 'd04ce91c-2c7e-4fff-bbd0-d49e393b047f',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Controls and displays',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 34,
    'uuid' => 'd1cb4fed-d67d-410f-ba65-1c4d0c4efc73',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Highway Trust Fund',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 32,
    'uuid' => 'd3f3d4d8-7246-4891-9fed-d877d39fb884',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Climate Change',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 10,
    'uuid' => 'd5ea705c-9a01-43c9-9beb-fc5368bc05c4',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Advanced Vehicle Technology Act',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 25,
    'uuid' => 'd9f6f853-caf9-44e6-80f8-10d051be0701',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'PRO-IP Act',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => 'e4ebc243-207a-4789-a5d1-e01f7d85f9e2',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Clean Energy',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 8,
    'uuid' => 'eb519948-b14b-43f6-a610-0290c80419c0',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Employee Free Choice Act',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => 'ec4a747f-170c-4646-b219-38da8cb1dcdf',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Healthy Families Act',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 6,
    'uuid' => 'edb31c0a-3671-4a51-879b-9317b9fa0fc1',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Family Fairness Act',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 5,
    'uuid' => 'ee96ef50-ec09-49d0-aeb1-08c8d358a916',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  $terms[] = array(
    'name' => 'Motorcoach Safety',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 46,
    'uuid' => 'fbe1b510-714a-4e00-b9b9-689e4b57b733',
    'vocabulary_machine_name' => 'topics',
    'url_alias' => array(),
  );
  return $terms;
}
